# Generated by Django 2.0.5 on 2018-05-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('session_id', 'username', 'time', 'seat_row', 'seat_column')},
        ),
    ]
